server:
  port: 8080
  
spring:
  application:
    name: weather-app
  jpa:
    hibernate:
      ddl-auto: update

logging:
  file: logs/weather.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR
    
config-weather:
  api:
    url: 'http://api.openweathermap.org/data/2.5/weather?q={city}&APPID={appid}'
    Key: 'abde2956874566e80d454ecfd4d9041e'
